name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.16"
            otp: "26"
          - elixir: "1.17"
            otp: "27"
          - elixir: "1.18"
            otp: "27"
            lint: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
      - uses: actions/cache@v4
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Dialyzer PLT Cache
        uses: actions/cache@v4
        if: ${{ matrix.lint }}
        id: plt-cache
        with:
          path: _build/test
          key: |
            ${{ runner.os }}-plt-otp${{ matrix.erlang }}-elixir${{ matrix.elixir }}

      - name: Install Dependencies
        run: mix deps.get

      # Create PLTs if no cache was found
      - name: Create PLTs
        if: ${{ matrix.lint && steps.cache-plt.outputs.cache-hit != 'true' }}
        run: mix dialyzer --plt

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run Tests
        run: mix test
        if: ${{ ! matrix.lint }}

      - name: Run Tests
        run: mix test --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run Dialyzer
        run: mix dialyzer
        if: ${{ matrix.lint }}
